apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-22a
  namespace: warehouse-22a
  labels:
    app: warehouse-22a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-22a
  template:
    metadata:
      labels:
        app: warehouse-22a
    spec:
      containers:
      - name: warehouse-22a
        image: matthieujbraga/warehouse-22a:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
