apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prd-dns-issuer
  namespace: warehouse-22a
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: m_braga@verizon.net
    privateKeySecretRef:
      name: letsencrypt-production-dns
    solvers:
    - dns01:
        rfc2136:
          nameserver: 192.168.224.100
          tsigKeyName: rndc-key
          tsigAlgorithm: HMACSHA256
          tsigSecretSecretRef:
            name: rndc-key-secret
            key: rndc-key
